services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/appnode_modules will be installed on the host machine and mounted inside the container
      - /app/node_modules